export const PRODUCTS = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
  };
  
  export const BLOG = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAIL: "FETCH_POSTS_FAIL",
  };
  
  export const SHOP_FILTER = {
    RESET_FILTERS: "RESET_FILTERS",
    SET_SORT: "SET_SORT",
    SET_SHOW: "SET_SHOW",
  };
  
  export const CART = {
    FETCH_CART: "FETCH_CART",
    FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
    FETCH_CART_FAIL: "FETCH_CART_FAIL",
  };
  
  export const WISHLIST = {
    FETCH_WISHLIST: "FETCH_WISHLIST",
    FETCH_WISHLIST_SUCCESS: "FETCH_WISHLIST_SUCCESS",
    FETCH_WISHLIST_FAIL: "FETCH_WISHLIST_FAIL",
  };
  
  export const COMPARE = {
    ADD_TO_COMPARE: "ADD_TO_COMPARE",
    REMOVE_FROM_COMPARE: "REMOVE_FROM_COMPARE",
  };
  
  export const BLOG_FILTER = {
    RESET_FILTERS: "RESET_FILTERS",
    SET_CATEGORY: "SET_CATEGORY",
    SET_TAG: "SET_TAG",
  };
  